apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: gitlab-data
  name: gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Mi
