apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8080
    - name: "50000"
      port: 50000
      targetPort: 50000
  selector:
    io.kompose.service: jenkins
