apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:lts
          name: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50000
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
            - name: docker-socket
              mountPath: /var/run/docker.sock
      restartPolicy: Always
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
