apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: jenkins-home
  name: jenkins-home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Mi
