apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: jira
  name: jira
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: jira
