apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: jira
  name: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jira
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: jira
    spec:
      containers:
        - env:
            - name: ATL_JDBC_PASSWORD
              value: jiradbpwd
            - name: ATL_JDBC_URL
              value: jdbc:postgresql://db:5432/jiradb
            - name: ATL_JDBC_USER
              value: jiradbuser
          image: atlassian/jira-software:latest
          name: jira
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/atlassian/application-data/jira
              name: jira-data
      restartPolicy: Always
      volumes:
        - name: jira-data
          persistentVolumeClaim:
            claimName: jira-data
