apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nexus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: nexus
    spec:
      containers:
        - image: sonatype/nexus3:latest
          name: nexus
          ports:
            - containerPort: 4502
              protocol: TCP
            - containerPort: 4503
              protocol: TCP
            - containerPort: 4504
              protocol: TCP
            - containerPort: 4505
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /opt/nexus-data
              name: nexus-data
      restartPolicy: Always
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data
