apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nexus-data
  name: nexus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4000Mi
