apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8081
    - name: "4502"
      port: 4502
      targetPort: 4502
    - name: "4503"
      port: 4503
      targetPort: 4503
    - name: "4504"
      port: 4504
      targetPort: 4504
    - name: "4505"
      port: 4505
      targetPort: 4505
  selector:
    io.kompose.service: nexus
