apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f required-environment.yml convert --provider kubernetes --out base_yamls/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: jiradb
            - name: POSTGRES_PASSWORD
              value: jiradbpwd
            - name: POSTGRES_USER
              value: jiradbuser
          image: postgres:13
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: jira-postgres-data
      restartPolicy: Always
      volumes:
        - name: jira-postgres-data
          persistentVolumeClaim:
            claimName: jira-postgres-data
